### ISSUE TITLE
Move documentation to Github

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#2]
The documentation should be moved to Github, so everything is gathered and accessible at one place.

**Comment by voipmeister** [comment]
Thanks, I will be following this closely. If there's anything to test on iOS, count me in.

Can you also manage the documentation at https://confluence-public.open-xchange.com/display/CoiW/COI+for+Beginners ?  SMTP is misspelled a few times as SMPT :-)

**Comment by Boehrsi** [comment]
@voipmeister thanks for your feedback and interest :). As soon as we have something up and running for the iOS part, I try to remember to ping you :). Regarding the typos, I forwarded that information and it should be already fixed by now :+1:.

**Comment by Boehrsi** [comment]
See https://github.com/open-xchange/ox-talk/wiki
