### ISSUE TITLE
Profile settings aren`t updated immediately

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#34]
**Describe the bug**
If the avatar, name or status message is changed, the changes aren't always applied to the profile view.

**To Reproduce**
Occurrence: [often]
1. Go to Profile
2. Click on Edit profile
3. Change values and apply them

**Expected behavior**
All changes are applied to the profile view.

**Additional context**
This happens due to the multiple responsibilities of the user_bloc. We need to split the displaying / loading logic and the change logic to fix this problem. A new user_change_bloc should get introduced. 

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-139)

**Comment by florianhaar** [comment]
Fixed
