### ISSUE TITLE
Chat title is not updated after contact name is changed

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#37]
**Describe the bug**
Chat title is not updated after contact name is changed.

**To Reproduce**
Occurrence: [always]
1. Create a chat with a single person
2. Change the name of that person in the contact view

**Expected behavior**
The chat name should also change.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-143)

**Comment by florianhaar** [comment]
Fiexed
