### ISSUE TITLE
Push messages?

### ISSUE THREAD

**Issue by pY4x3g** [open-xchange/ox-talk#40]
I do not find any information on how the problem with push messages will be handled in android (and iOS).
Since android 8 you can only implement push messages with the usage of FCM (firebase cloud messaging) without draining the battery as far as I know.
Or did I just miss something?

**Comment by Boehrsi** [comment]
You are completely right @pY4x3g, FCM is more or less the only way to implement push "efficient" on modern Android systems and on iOS it's pretty similar. We are right now in the phase of "foreground only" with the OX Talk app, but push is planned. To implement a reliable solution we have to use the solutions Google and Apple provide.
Currently we plan to leverage the Web Push Standard for enabling push. As push certificates must remain private and client specific the client developers need to provide a push service. This service is then triggered by the IMAP backend, once the user has registered for it and there is a new incoming message.

**Comment by pY4x3g** [comment]
thanks for the fast clarification!

**Comment by Boehrsi** [comment]
No problem, if you have more questions feel free to open a new issue. :+1:
