### ISSUE TITLE
Key exchange for encrypted communication

### ISSUE THREAD

**Issue by hdino** [open-xchange/ox-talk#42]
Often, when you want to exchange contact information, people enter the contact information into their phone. Some applications and messengers, such as Line, allow the user to exchange this information by scanning a QR code from the other phone. Such a code could also contain the peer's public key so that exchanging this information can be made fairly secure. Perhaps symbolized by a green lock on the chat screen (and a gray lock if the public key has been exchanged in a less trustworthy way) :-)

**Comment by Boehrsi** [comment]
Something like this is definitely planned. Happily the underlying logic layer (https://github.com/deltachat/deltachat-core) already supports this sort of verification. But for now I can't give an ETA or similar, but it's definitely planned.

**Comment by hdino** [comment]
That's great to hear! A few months ago I started a very similar IMAP-based messenger project, which I'll give up now in favour of ox-talk, but I think this key exchange was one of the best things on its feature list.

**Comment by Boehrsi** [comment]
@hdino thanks for your support! And exchanging contact data directly in a simple and also secure way is a pretty nice feature, that's true. I could imagine you could also be interested in https://github.com/deltachat/deltachat-android. This project is an Android app also using https://github.com/deltachat/deltachat-core.
