### ISSUE TITLE
Message Actions - Copy

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#53]
**Is your feature request related to a problem? Please describe.**
The user should be able to copy a message from the chat view.

**Describe the solution you'd like**
Long pressing on a message should add the given text to the clipboard. This action is only available for text. 

**Additional context**
- Multi select will be added later.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-158)

**Comment by florianhaar** [comment]
implemented
