### ISSUE TITLE
Add new message counter for chats

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#54]
**Is your feature request related to a problem? Please describe.**
The user should be able to see if new messages exist, directly in the chat list.

**Describe the solution you'd like**
A small indicator in every chat list item should show the number of new messages (1-99 or 99+). If no new message exists, no indicator should be visible. The DCC should already be able to deliver the required data.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-159)

**Comment by florianhaar** [comment]
implemented and merged
