### ISSUE TITLE
Add search / filtering for the contact list

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#59]
**Is your feature request related to a problem? Please describe.**
The user should be able to filter / search for contacts in the contact list.

**Describe the solution you'd like**
- Use the given designs
- Performing a search should use given DCC functions https://c.delta.chat/classdc__context__t.html#a32f1458afcacf034148952305bf60abe
- A list of results should be shown / the list should get filtered
- Tapping opens the contact in edit mode

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-104)

**Comment by florianhaar** [comment]
implemented
