### ISSUE TITLE
"Import Autocrypt setup message" page is not scrollable

### ISSUE THREAD

**Issue by matthesatox** [open-xchange/ox-talk#611]
**Describe the bug**
"Import Autocrypt setup message" page is not scrollable. This leads on devices with smaller displays, e.g. 4", to the problem, that the input box for the code isn't visible for the user. 

**To Reproduce**
Occurrence: [always / 5 out of 10 times / rarely]
1. Login to coi on two different devices
2. Initiate key transfer on one device
3. copy the code
4. open message on second device and tab on received Autocrypt device
5. Try  scroll the page to enter code

**Expected behavior**
"Import Autocrypt setup message" page should be scrollable for the user, so that he can see the input box

**Screenshots**
![IMG_5491](https://user-images.githubusercontent.com/62440505/84490520-93f25380-aca3-11ea-8ebb-a79f67f2d0f1.PNG)

**App information (please complete the following information):**
 - App version: 0.700.3
 - Plugin version: [e.g. 0.4.0]
 - Delta Chat Core version: [e.g. 0.40.0]
 - Flutter version: [e.g. 1.0]

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2016)
 - OS: iOS 13.5

**Additional context**

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-???).

**Comment by Boehrsi** [comment]
Merged and working, waiting for builds.
