### ISSUE TITLE
Provide notifications for incoming message while in foreground

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#62]
**Is your feature request related to a problem? Please describe.**
The user should be informed as soon as a new message arrives. A notification should be created if:
- The user has the app in the foreground
- Is not in the chat the message belongs to

**Describe the solution you'd like**
We should add a global listeners for messages, which creates those notifications. The listener should always be informed if the app is visible and which view is open. Doing this the listener would be able to decide if a notification should be shown.

**Additional context**
If is important to assure notifications aren't displayed multiple times. We have to add a Flutter plugin to access notifications.
This ticket only handles the actual loading / refreshing part. The UI is done in https://github.com/open-xchange/ox-talk/issues/87.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-164)

**Comment by florianhaar** [comment]
done
