### ISSUE TITLE
Contacts from invites are shown in the contact list

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#66]
**Describe the bug**
If a new invite appears the corresponding contact is shown in the normal contact list.

**To Reproduce**
Occurrence: [always]
1. New invite appears

**Expected behavior**
Contacts not added by the user are not shown in the normal contact list.

**Additional context**
This happens due to our repository handling. We have to split contacts added by invites and contacts added by the user. Therefore we will use two separate repositories.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-166)

**Comment by florianhaar** [comment]
Fixed and merged
