### ISSUE TITLE
Key Handling - Export / import keys

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#68]
**Is your feature request related to a problem? Please describe.**
The user needs to be able to export / import there secret keys.

**Describe the solution you'd like**
The settings should provide an entry to export / import the automatically setup keys. This entry should be secured be e.g. a pin or the already set lock pattern.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-169)

**Comment by webratte** [comment]
It would be great if you could add this to the next release.

So I could test ox talk side by side with Delta Chat by using the same keys.

What do you think, can you realize it for the next preview version?

Thank.you in advance

**Comment by Boehrsi** [comment]
Hi @webratte,

sorry I totally overlooked your comment. We are releasing probably today another version, which sadly not contain this feature. I will have a look if it could fit into next release. Sorry again for the late reply.

**Comment by webratte** [comment]
There's no need for an apology. 😀

**Comment by Boehrsi** [comment]
Will probably be added this week. :+1:

**Comment by webratte** [comment]
Great 👍

**Comment by Boehrsi** [comment]
@webratte this feature will probably be released next Monday as part of our next release. :)

**Comment by webratte** [comment]
Great.
I'm looking forward for this.
