### ISSUE TITLE
Adjust time indicator in chat view

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#7]
Messages currently only have a time value displayed to the user in the chat view. We need to adjust that to also display the date, if the message wasn't sent at the same day. If possible we should add a scrollable date marker.

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-117)

**Comment by Boehrsi** [comment]
It could be a good idea to use https://docs.flutter.io/flutter/widgets/ListView/ListView.separated.html for date indication within the list without altering the current "show time only" widget.

**Comment by florianhaar** [comment]
implemented and merged
