### ISSUE TITLE
Chat list item UI problems

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#81]
**Describe the bug**

- The message preview is cut by the date / time indicator
- The divider is cut by the date / time indicator and by the message counter

**To Reproduce**
Occurrence: [always ]
1. Open the chat list
2. Receive a new message in an existing chat

**Expected behavior**
Nothing is cut and all possible space is used.

**Additional context**
Currently the main layout displays elements horizontally beside each other. The name and preview on the left, the date and the message counter on the right. We should move the date and the message counter inside the structure, so they are displayed right beside the actual name / preview views and not on the root level. This should avoid the UI problems and lead to more flexibility.

**Comment by florianhaar** [comment]
https://github.com/open-xchange/ox-talk/pull/86
