### ISSUE TITLE
Group invite problems

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-talk#90]
**Describe the bug**

- Sometimes group invites are created as one to one chats with the person whom sent the message
- Right after creation not all group contacts are displayed in the group detail screen

**Expected behavior**
Group creation and group contact handling should work.

**Additional context**

- Contacts are probably missing due to missing initialization of the required repository objects during group creation
- The messy situation while accepting group invites needs further investigation

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-191)

**Comment by florianhaar** [comment]
Fixed and merged
